services:
  clio:
    build: .
    image: ttsu/chlio
    container_name: clio-app
    ports:
      - "${PORT:-4191}:${PORT:-4191}"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=production
      - CLIO_DATA_DIR=/data
      - PORT=${PORT:-4191}
    volumes:
      - clio-data:/data

volumes:
  clio-data:
