// Clio design system — window.Clio. Types are documentation; props mirror each component README.
import type { ReactNode, CSSProperties, ButtonHTMLAttributes } from 'react';
type Tint = 'rose' | 'sky' | 'sage' | 'amber' | 'lilac' | 'stone';
type Status = 'todo' | 'inprogress' | 'review' | 'done';
type Priority = 'high' | 'medium' | 'low';
type IconName = string; // see ICONS keys: home, hub, cloud, kanban, calendar, canvas, folder, pdf, notebook, spark, …
export declare function Icon(p: { name: IconName; size?: number; stroke?: number; className?: string; style?: CSSProperties }): JSX.Element;
export declare function Button(p: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'ai' | 'danger'; size?: 'sm'; icon?: IconName; iconRight?: IconName; block?: boolean }): JSX.Element;
export declare function IconButton(p: ButtonHTMLAttributes<HTMLButtonElement> & { icon: IconName; label: string; active?: boolean; size?: 'lg'; outlined?: boolean; dot?: boolean; iconSize?: number }): JSX.Element;
export declare function SegmentedControl(p: { options: { value: string; label: string; icon?: IconName }[]; value?: string; onChange?: (v: string) => void; iconOnly?: boolean }): JSX.Element;
export declare function SearchField(p: { placeholder?: string; shortcut?: string; value?: string; onChange?: (e: any) => void; style?: CSSProperties }): JSX.Element;
export declare function TextField(p: { label?: string; hint?: string; error?: string; multiline?: boolean; mono?: boolean; [attr: string]: any }): JSX.Element;
export declare function Checkbox(p: { checked?: boolean; defaultChecked?: boolean; onChange?: (v: boolean) => void; strike?: boolean; children?: ReactNode }): JSX.Element;
export declare function Switch(p: { on?: boolean; onChange?: (v: boolean) => void; label: string }): JSX.Element;
export declare function ColorPicker(p: { colors?: string[]; value?: string; onChange?: (c: string) => void; allowCustom?: boolean; label?: string }): JSX.Element;
export declare function Tag(p: { tone?: Tint; children: ReactNode; onRemove?: () => void; outline?: boolean; icon?: IconName }): JSX.Element;
export declare function StatusPill(p: { status?: Status; count?: number }): JSX.Element;
export declare function PriorityFlag(p: { priority?: Priority }): JSX.Element;
export declare function DeltaChip(p: { value: number; suffix?: string }): JSX.Element;
export declare function Kbd(p: { children: ReactNode }): JSX.Element;
export declare function Avatar(p: { name?: string; src?: string; size?: number; tone?: Tint }): JSX.Element;
export declare function ProgressDots(p: { value?: number; total?: number; tone?: Tint; label?: string }): JSX.Element;
export declare function Window(p: { children: ReactNode; flat?: boolean; style?: CSSProperties }): JSX.Element;
export declare function Sidebar(p: { activeView?: 'home' | 'projects' | 'nextcloud' | 'kanban' | 'calendar' | 'canvas'; projects?: { id: string; name: string; color: Tint; count?: number; active?: boolean }[]; tree?: TreeNode[]; tags?: { name: string; color: Tint }[]; activeFileId?: string; user?: { name: string; email: string }; sync?: 'connected' | 'connecting' | 'failed' | 'idle'; logoLight?: string; logoDark?: string; counts?: Record<string, number>; onNavigate?: (view: string) => void }): JSX.Element;
type TreeNode = { id: string; type: 'folder' | 'pdf' | 'notebook' | 'markdown' | 'sticky'; name: string; open?: boolean; children?: TreeNode[] };
export declare function NavItem(p: { icon?: IconName; label: string; active?: boolean; count?: number; color?: Tint; onClick?: () => void }): JSX.Element;
export declare function NavSection(p: { title: string; actions?: { icon: IconName; label: string; onClick?: () => void }[]; children: ReactNode }): JSX.Element;
export declare function TopBar(p: { crumbs: string[]; sidebarOpen?: boolean; recording?: boolean; panelOpen?: boolean; theme?: 'light' | 'dark'; onToggleTheme?: () => void; onTogglePanel?: () => void; showDownload?: boolean; children?: ReactNode }): JSX.Element;
export declare function ViewHeader(p: { title: string; subtitle?: string; overline?: string; actions?: ReactNode }): JSX.Element;
export declare function SectionHeader(p: { title: string; icon?: IconName; count?: number; actions?: ReactNode }): JSX.Element;
export declare function Card(p: { children: ReactNode; hover?: boolean; className?: string; style?: CSSProperties }): JSX.Element;
export declare function CardTitle(p: { icon?: IconName; title: string; info?: boolean; actions?: boolean }): JSX.Element;
export declare function NoteGroup(p: { title: string; tone?: Tint; onAdd?: () => void; children: ReactNode }): JSX.Element;
export declare function NoteCard(p: { title: string; subtitle?: string; body?: string; highlight?: string; tags?: { name: string; color: Tint }[]; kind?: 'markdown' | 'notebook' | 'pdf' | 'sticky'; updated?: string }): JSX.Element;
export declare function ProjectCard(p: { name: string; context?: string; description?: string; color?: Tint; starred?: boolean; status?: Status; activity?: string; progress?: number }): JSX.Element;
export declare function ProjectRow(p: { name: string; context?: string; color?: Tint; starred?: boolean; status?: Status; activity?: string; notes?: number }): JSX.Element;
export declare function AddTile(p: { label?: string; onClick?: () => void; minHeight?: number }): JSX.Element;
export declare function TaskCard(p: { id: string; title: string; description?: string; priority?: Priority; due?: string; dueState?: 'soon' | 'late'; project?: string; projectColor?: Tint; dragging?: boolean; onOpen?: () => void }): JSX.Element;
export declare function KanbanColumn(p: { status: Status; count?: number; over?: boolean; onAdd?: () => void; children?: ReactNode }): JSX.Element;
export declare function FolderCard(p: { name: string; count?: string; tone?: Tint; peek?: number }): JSX.Element;
export declare function PaperCard(p: { title: string; authors?: string; arxiv?: string; pages?: number; tags?: { name: string; color: Tint }[]; annotated?: number; status?: 'local' }): JSX.Element;
export declare function StickyNote(p: { title: string; body: string; tone?: Tint; when?: string; dragging?: boolean }): JSX.Element;
export declare function TodoList(p: { items: { id?: string; text: string; completed?: boolean; dueTime?: string; soon?: boolean }[]; showAdd?: boolean; onAddPlaceholder?: string }): JSX.Element;
export declare function DailyCard(p: { date: string; icon?: IconName; prose?: ReactNode; tasksTitle?: string; tasks?: any[]; footer?: string; tag?: string; showAdd?: boolean }): JSX.Element;
export declare function AgendaItem(p: { time: string; title: string; detail?: string; tone?: Tint; done?: boolean }): JSX.Element;
export declare function BarChart(p: { data: number[]; labels?: string[]; active?: number; average?: number; height?: number; tip?: string }): JSX.Element;
export declare function StatCard(p: { icon?: IconName; title: string; value: string | number; unit?: string; delta?: number; deltaLabel?: string; chart?: object }): JSX.Element;
export declare function StreakCard(p: { days: number; week: number[]; todayIndex?: number; tasksDone?: number; notesLogged?: number }): JSX.Element;
export declare function ChatMessage(p: { role?: 'user' | 'assistant'; thought?: string; streaming?: boolean; actions?: boolean; children: ReactNode }): JSX.Element;
export declare function Composer(p: { context?: string[]; placeholder?: string; model?: string; busy?: boolean }): JSX.Element;
export declare function SmartNote(p: { title: string; status?: 'idle' | 'loading' | 'done' | 'error'; open?: boolean; children?: ReactNode }): JSX.Element;
export declare function AIPanel(p: { tab?: 'chat' | 'notes'; file?: string; children: ReactNode | ((tab: string) => ReactNode); footer?: ReactNode; onClose?: () => void }): JSX.Element;
export declare function ToolDock(p: { active?: string; color?: string; onSelect?: (t: string) => void; onUndo?: () => void; onRedo?: () => void }): JSX.Element;
export declare function ToolPopover(p: { tool?: string; size?: number; color?: string; palmRejection?: boolean }): JSX.Element;
export declare function NotebookPage(p: { width?: number; height?: number; ruled?: boolean; lineSpacing?: number; page?: string; children?: ReactNode }): JSX.Element;
export declare function CanvasTagBar(p: { tags: { name: string; color: Tint }[] }): JSX.Element;
export declare function MiniCalendar(p: { month?: string; startOffset?: number; days?: number; today?: number; selected?: number; marked?: number[] }): JSX.Element;
export declare function EventBlock(p: { title: string; time?: string; tone?: Tint; done?: boolean; compact?: boolean; style?: CSSProperties }): JSX.Element;
export declare function Modal(p: { title: string; description?: string; children: ReactNode; footer?: ReactNode; onClose?: () => void; width?: number; inline?: boolean }): JSX.Element;
export declare function Menu(p: { items: ({ icon: IconName; label: string; shortcut?: string; danger?: boolean } | '-')[] }): JSX.Element;
export declare function Tooltip(p: { children: ReactNode; shortcut?: string }): JSX.Element;
export declare function Banner(p: { tone?: 'info' | 'ai' | 'success' | 'danger'; icon?: IconName; title?: string; children: ReactNode; action?: ReactNode }): JSX.Element;
export declare function EmptyState(p: { icon?: IconName; title: string; children: ReactNode; action?: ReactNode }): JSX.Element;
export declare function QuickActions(p: { items: { icon: IconName; label: string; tone?: Tint }[] }): JSX.Element;
export declare function ConnectionForm(p: { status?: 'connected' | 'connecting' | 'failed' | 'idle'; url?: string; username?: string; papersPath?: string; syncPath?: string }): JSX.Element;
